import type { Product, Category, Customer, Sale } from "@shared/schema";

export const mockCategories: Category[] = [
  { id: 1, name: "Lanches", description: "Hambúrgueres e sanduíches" },
  { id: 2, name: "Bebidas", description: "Refrigerantes, sucos e águas" },
  { id: 3, name: "Acompanhamentos", description: "Batatas e porções" },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "X-Burger Completo",
    code: "001",
    barcode: "7891234567890",
    price: "15.90",
    category_id: 1,
    stock_quantity: 25,
    min_stock: 5,
    is_active: true,
    created_at: new Date(),
  },
  {
    id: 2,
    name: "Refrigerante Lata",
    code: "002",
    barcode: "7891234567891",
    price: "5.50",
    category_id: 2,
    stock_quantity: 8,
    min_stock: 10,
    is_active: true,
    created_at: new Date(),
  },
  {
    id: 3,
    name: "Batata Frita",
    code: "003",
    barcode: "7891234567892",
    price: "8.90",
    category_id: 3,
    stock_quantity: 15,
    min_stock: 5,
    is_active: true,
    created_at: new Date(),
  },
  {
    id: 4,
    name: "Água 500ml",
    code: "004",
    barcode: "7891234567893",
    price: "3.00",
    category_id: 2,
    stock_quantity: 20,
    min_stock: 10,
    is_active: true,
    created_at: new Date(),
  },
  {
    id: 5,
    name: "X-Salada",
    code: "005",
    barcode: "7891234567894",
    price: "12.90",
    category_id: 1,
    stock_quantity: 18,
    min_stock: 5,
    is_active: true,
    created_at: new Date(),
  },
  {
    id: 6,
    name: "Suco Natural",
    code: "006",
    barcode: "7891234567895",
    price: "7.50",
    category_id: 2,
    stock_quantity: 12,
    min_stock: 5,
    is_active: true,
    created_at: new Date(),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 1,
    name: "João Silva",
    cpf: "123.456.789-00",
    phone: "(11) 99999-9999",
    email: "joao@email.com",
    created_at: new Date(),
  },
  {
    id: 2,
    name: "Maria Santos",
    cpf: "987.654.321-00",
    phone: "(11) 88888-8888",
    email: "maria@email.com",
    created_at: new Date(),
  },
  {
    id: 3,
    name: "Pedro Costa",
    phone: "(11) 77777-7777",
    email: "pedro@email.com",
    created_at: new Date(),
  },
];

export const mockSales: Sale[] = [
  {
    id: 1,
    customer_id: 1,
    total_amount: "21.40",
    payment_method: "card",
    status: "completed",
    created_at: new Date(),
  },
  {
    id: 2,
    customer_id: null,
    total_amount: "11.90",
    payment_method: "cash",
    status: "completed",
    created_at: new Date(),
  },
  {
    id: 3,
    customer_id: 2,
    total_amount: "20.40",
    payment_method: "pix",
    status: "completed",
    created_at: new Date(),
  },
];
